name: Content Check

on:
  push:
  pull_request:

jobs:
  check-markdown:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: Lint markdown
        uses: avto-dev/markdown-lint@v1
        with:
          config: './.markdownlint.jsonc'
          args: './content'
